title: My GitHub Page
description: >- # this means to ignore newlines until "baseurl:"
  This is my GitHub page.
baseurl: "" # the subpath of your site, e.g. /blog
header_pages:
  - CSILund_sequencing.md
url: "https://resabut.github.io" # the base hostname & protocol for your site
markdown: kramdown
theme: minima